language: ruby
cache: bundler
before_install: 
  - gem install bundler
install: 
  - bundle install --jobs=3 --retry=3
script: 
  - "./build"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build