language: ruby
cache: bundler
before_install: 
  - chmod +x build.sh
  - gem install bundler
install: 
  - bundle install --jobs=3 --retry=3
script: 
  - "./build.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer