language: ruby
rvm:
- 2.4.2
- 2.6

install: 
  - bundle install

# script: ./script/cibuild
script: jekyll build && htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer


sudo: false # route your build to the container-based infrastructure for a faster build