language: ruby
rvm:
- 2.5
- 2.6
cache: bundler
before_install: 
  - gem install bundler
  - gem update bundler
install: 
  - bundle install
script: 
  - "./build"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build