# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sean Nam
email: sangwoo@seannam.com
description: >- # this means to ignore newlines until "baseurl:"
  UCSD Computer Science Student.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seannam.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Sean Nam'
bio: >
  UC San Diego Computer Science major. Graduating Spring 2019.
author_image: "/assets/images/author.jpg"
twitter_username: nam_sean
github_username:  seannam

# Google Analytics
analytics_id: "UA-114674539-1"

# Build settings
permalink: /:title/

mailchimp-list: 
  user-id: 37cae49f6d9c8c7b096f2713a,
  list-id: d7b130ed60

# Travis CI settings
username: seannam
repo: seannam.github.io
branch: master
destination: _site/
safe: false

markdown: kramdown

kramdown:
  parse_block_html: true

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration

plugins:
  - jekyll-paginate
  - jekyll-gist
